# Simple workflow for deploying static content to GitHub Pages
name: Collect documentation from projects and deploy to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Install Python dependencies
        run: pip3 install invoke==2.2.0 Markdown==3.7
        # run: pip3 install -r requirements.txt
      - name: Get repository data-exchange-protocol
        uses: actions/checkout@v3
        with:
          repository: "wbcsd/data-exchange-protocol"
          path: "temp/data-exchange-protocol"
      - name: Get repository pact-directory-service        
        uses: actions/checkout@v3
        with:
          repository: "wbcsd/pact-directory-service"
          path: "temp/pact-directory-service"
      - name: Get repository pact-conformance-service        
        uses: actions/checkout@v3
        with:
          repository: "wbcsd/pact-conformance-service"
          path: "temp/pact-conformance-service"
      - name: Get repository tr        
        uses: actions/checkout@v3
        with:
          repository: "wbcsd/tr"
          path: "temp/tr"
      - name: Build specs
        run: invoke build
        shell: bash
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "build"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
